settings:
  best:
    quality: hdtv+ <=720p !10bit
    target: 720p
    timeframe: 6 hours
    propers: 12 hours
  better:
    quality: hdtv+ <=720p !10bit
    target: <720p
    timeframe: 6 hours
    propers: 12 hours
  average:
    quality: hdtv+ <=720p !10bit
    target: <720p
    timeframe: 6 hours
    propers: 12 hours
    set:
      path: "/home/elboletaire/Vídeos/Series/{{ series_name }}/{{ series_season }}a Temporada/"
      content_filename: "{{ series_name }} - {{ series_id }} {{ tvdb_ep_name | default('Unknown ep. name') }}"
  documentaries:
    quality: hdtv+ <=720p !10bit
    target: <720p
    timeframe: 6 hours
    propers: 12 hours
  anime:
    quality: hdtv+ <=720p !10bit
    target: <720p
    timeframe: 6 hours
    propers: 12 hours
  japanime:
    quality: hdtv+ <=720p !10bit
    target: <720p
    timeframe: 6 hours
    propers: 12 hours

