#!/bin/bash

if [[ -x ./vendor/bin/phpunit ]]; then
  ./vendor/bin/phpunit --coverage-text
  rc=$?
  if [[ $rc != 0 ]]; then
    exit $rc
  fi
fi

# Detect JS package manager and run tests if applicable
if [[ -f ./package.json ]] && grep '"test"' ./package.json > /dev/null; then
  if [[ -f ./package.json ]]; then
    pkg_mgr_field=$(grep '"packageManager"' ./package.json | head -1 | sed -E 's/.*"packageManager": *"([^"]+)".*/\1/')
    if [[ -n "$pkg_mgr_field" ]]; then
      pkg_mgr=$(echo "$pkg_mgr_field" | cut -d@ -f1)
    else
      # Fallback detection
      if [[ -f yarn.lock ]]; then
        pkg_mgr="yarn"
      elif [[ -f pnpm-lock.yaml ]]; then
        pkg_mgr="pnpm"
      elif [[ -f package-lock.json ]]; then
        pkg_mgr="npm"
      else
        pkg_mgr="yarn"
      fi
    fi
  fi

  echo "Detected package manager: $pkg_mgr"

  CI=true $pkg_mgr test
  rc=$?
  if [[ $rc != 0 ]]; then
    exit $rc
  fi
fi

if [[ -f ./makefile ]] && grep 'test:' ./makefile > /dev/null; then
	CI=true make test
	rc=$?
  if [[ $rc != 0 ]]; then
    exit $rc
  fi
fi


exit 0
