#!/bin/bash

if [[ -x ./vendor/bin/phpunit ]]; then
  ./vendor/bin/phpunit --coverage-text
  rc=$?
  if [[ $rc != 0 ]]; then
    exit $rc
  fi
fi

if [[ -d ./node_modules/.bin && -f ./package.json ]] && grep '"test"' ./package.json > /dev/null; then
  CI=true yarn test
  rc=$?
  if [[ $rc != 0 ]]; then
    exit $rc
  fi
fi

if [[ -f ./makefile ]] && grep 'test:' ./makefile > /dev/null; then
	CI=true make test
	rc=$?
  if [[ $rc != 0 ]]; then
    exit $rc
  fi
fi


exit 0
