#!/bin/bash

if [[ -x ./vendor/bin/phpunit ]]; then
  ./vendor/bin/phpunit --coverage-text
  rc=$?
  if [[ $rc != 0 ]]; then
    exit $rc
  fi
fi

if [[ -d ./node_modules/.bin && -d ./test && -f ./package.json ]]; then
  CI=true npm test
  rc=$?
  if [[ $rc != 0 ]]; then
    exit $rc
  fi
fi


exit 0
